version: '3.3'
services:
 ignite:
  build: 
    context: .
    dockerfile: Dockerfile
  environment:
   - IGNITE_QUIET=false
  ports:
   - "10800:10800" # JDBC
   - "10900:10900" # Thin client
   - "11211:11211" # REST
   - "47100:47100" # Java Service Provider Interface (SPI) Communication
   - "47500-47599:47500-47599" # Java Service Provider Interface (SPI) Discovery
   - "48100:48100" # Shared memory port
   - "49112:49112" # Java Management Extension (JMX)
  volumes:
   - ..:/project

